remote_theme: "jekyll/minima@1e8a445"
title: "Furkan Safa Altunyuva"
description: "Blog posts about my homework and repositories."
header_pages:
  - about.md
minima:
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/fsaltunyuva"
  show_excerpts: true
